### ISSUE TITLE
Obtain photo-z for HSC data

### ISSUE THREAD

**Issue by camposandro** [lincc-frameworks-mask-incubator/corrgi#17]
Find and download the point-estimated photo-z (w/ SFR, etc) for the HSC data. They are normalized in a SQL database.

**Comment by samotracio** [comment]
Data for [DEMP](https://hsc-release.mtk.nao.ac.jp/doc/wp-content/uploads/2022/08/pdr3_photoz.pdf) photoz point estimates is ready and has been merged in a 21 GB fits table (507215729 rows x 8 cols). It contains object_id + photoz_columns + ra + dec

_/ocean/projects/phy210048p/shared/hscpz/demp_point/demp_merged.fits_

Note : this contains only some columns, related with the "_best" version among various estimates, which is the version recommended by HSC
