### ISSUE TITLE
Call gundam with dataframes

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks-mask-incubator/corrgi#6]
Given two dataframes from LSDB, projected bins, and other correlation arguments, call gundam correlation counting.

This may necessitate calling fortran code from corrgi (or adding a new method to gundam to accept np arrays directly), instead of going through gundam's existing python API, as they rely on `astropy.Table` and will calculate the bin projection for each call.

**Comment by camposandro** [comment]
Corrgi is already able to compute the angular correlation counts, and it has been prepared to further wrap the redshift and projected functions. Closed by #8.
